name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag home4u/home4u-ui

    - name: Save docker file
      run: docker save home4u/home4u-ui > home4u-ui.tar

    - name: Upload Docker Image TAR as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: home4u-ui-tar
        path: home4u-ui.tar

    - name: update artifacts
      run: |
        curl "http://149.102.135.15:8080/job/Home4U-UI/build?token=w34iK1MmmaOJfZ6deuFeRvtzuxgOxFoqQHoRh2E74lXs4tVyS2jUZWHj0VgYCQFP"
