name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag home4u/home4u-ui && docker save home4u/home4u-ui > home4u-ui.tar

    - name: Save docker file
      run: docker save home4u/home4u-ui > home4u-ui.tar

    - name: Push docker tar file
      run: |
        git add home4u-ui.tar
        git commit -m "Save Docker image as TAR file"
        git push origin main
